### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by alastair** [MTG/acousticbrainz-client#9]
- [x] multicore
- [ ]  fingerprint lookup to get mbids for files with no tag
- [x] make output/logging better
- [x] better error reporting
- [x] Compile extractor with small static libav
- [x] fix lossless detection
- [x] make the processed file storage more optimal (#7)
- [x] look for the extractor better, including in $PATH, and with different arch suffixes
- [x] setup.py, pypi
- [x] fix the readme
